### ISSUE TITLE
Table with headers

### ISSUE THREAD

**Issue by HardlyMirage** [tangbc/vue-virtual-scroll-list#14]
Any idea how we can implement a `<table>` with `<thead>`?

```
<template>
    <table>
        <thead>
            <tr>
                <th v-for="column in columns">{{ column.title }}</th>
            </tr>
        </thead>
         <virtualList rtag="div" :size="62" :remain="20" wtag="tbody"> 
            <tr :key="item.id" v-for="(item, index) in items">
                <td v-for="column in columns">{{ item[column.field] }}</td>
            </tr>
         </virtualList>
    </table>
</template>
```

This throws a `<div>` between `<tbody>` and `<table>` messing up the layout.

**Comment by tangbc** [comment]
By this component implementation principle, it's difficult, if you add other non scrolling elements,  it will make the array index, item height and all paddings calculation messy or unmanageable, because `thead` is not a calculated `item`. In this case, why not use div layout instead of table layout ? 😂
