### ISSUE TITLE
How should I handle when an item in the invisible area is resized?

### ISSUE THREAD

**Issue by baco16g** [tangbc/vue-virtual-scroll-list#214]
This is a very rare case.

## Describe
* I want to resize an item that is in the invisible area.
* If I resize the item in the upper invisible area, the calculation of `padFront` will be misaligned.
* Is it possible to display correctly in the above case with this library?

## To Reproduce
1. Access the demo.
2. Scroll down until the range changes.
3. Click a button. `Change size of index 4`
4. Scroll up until the range changes.

## Reproduce demo
https://codesandbox.io/s/live-demo-virtual-list-zqbz9

**Comment by baco16g** [comment]
![May-15-2020 10-26-35](https://user-images.githubusercontent.com/20724254/82001655-a2465300-9696-11ea-8d32-6b184a292e56.gif)

**Comment by tangbc** [comment]
The reason is that `padFront` only update in next range change (trigger by start and end changed), so may separate updating `range` and `padding`, I will try this idea.

**Comment by tangbc** [comment]
Its my research conclusion:

1. The first render range index is 0 ~ 30.
2. Then you scroll down, suppose render range becomes 10 ~ 40.
3. Now you try to change index 4 data which is not rendering in real dom.
4. We cannot know the dom size change due to index 4 data change unitl it is scrolled into render range.

So, this scene maybe not be solved completely in any virtual list component.
