### ISSUE TITLE
Empty wtag

### ISSUE THREAD

**Issue by johannes-z** [tangbc/vue-virtual-scroll-list#25]
Can you make the wtag optional and leave the styling to the user? The problem I have is with tables, where the `rtag` would be the `tbody` and `wtag` the `tr`. For the `tr` I'm using my own component and I don't require the wrapper element, because I can style the component myself. Leaving the `wtag` attribute empty does not work as is though.

**Comment by tangbc** [comment]
As far as I understand your problem, that cannot support in this component.

Both `rtag` (root element) and `wtag` (wrapper element) are required and created by virtual-list interior/private, root element is used to make a fixed height viewport so that it's scrollable and wrapper element is used to make a height enough container to contain all `<item/>`s, handle scroll offset, padding and other calculation. The only your own component is just `<item/>`.

If give the wrapper element to user custom define, virtual-list inner padding, scroll and other calculating data will be lost or need handle by user (outside virtual-list, but it's difficult and unreasonable).

That's my point of view, or do I understand your case mistake ? can you provide an online demo for detail ？

**Comment by riksnelders** [comment]
I also cannot use this component simply cuz of the use of tables.. 
Any fix for this?
