### ISSUE TITLE
Use another container tag

### ISSUE THREAD

**Issue by timwis** [tangbc/vue-virtual-scroll-list#4]
I'd like to use this library within a `<table>`, so I'd like the parent element to be a `<tbody>`. But it appears it's hardcoded to use a `<div>`. Unless I'm overlooking something?

**Comment by tangbc** [comment]
@timwis thank you for reminding this feature, so I plan to support it soon.

**Comment by tangbc** [comment]
This feature is published, see https://github.com/tangbc/vue-virtual-scroll-list#support-props-type, support `rtag` to designate virtual-list root element tag and `wtag` to designate padding wrapper element tag. 

In order to use scrollbar and fix height on `<table>` or `<tbody>` element, it has to set their style here with: `display: block;` because they are both `inline-element`.

Looking forward to the follow-up use feedback of this featrue.

**Comment by timwis** [comment]
Thanks for the quick delivery!

**Comment by HardlyMirage** [comment]
Any idea how we can implement a `<table>` with `<thead>`?

```
<template>
    <table class="ui single line table">
        <thead>
            <tr>
                <th v-for="column in columns">{{ column.title }}</th>
            </tr>
        </thead>
         <virtualList ref="scroll" rtag="div" :size="62" :remain="20" wtag="tbody"> 
            <tr :key="item.id" v-for="(item, index) in items">
                <td v-for="column in columns">{{ item[column.field] }}</td>
            </tr>
         </virtualList>
    </table>
</template>
```

This throws a `<div>` between `<tbody>` and `<table>` messing up the layout.
