### ISSUE TITLE
the props 'start&offset' are not work.

### ISSUE THREAD

**Issue by MLYC** [tangbc/vue-virtual-scroll-list#40]
the props 'start&offset' are not work.

**Comment by tangbc** [comment]
Can you offer more details about your case.

**Comment by MLYC** [comment]
index.js 283
          // set manual scroll top.
            setScrollTop: function (scrollTop) {
              var _this = this
              setTimeout(function () {
                _this.$refs.vsl.scrollTop = scrollTop
              },1)
            },
I fix it with setTimeout();

**Comment by tangbc** [comment]
I don't realy know where the specific problem is, but in most cases it's wrong for using `setTimeout` to solve a problem.

**Comment by MLYC** [comment]
in the 'index.js' line 283,it can't set the scrollTop

**Comment by aldenozburn** [comment]
Since the start prop is not updated upon scroll unless you handle that yourself, you can't rely on it to be up to date. 

This means that if you have the start prop variable set to 0 for instance, then scroll somewhere else, then set the prop value to 0 again (the same value), the ui will not update, since as far as it is concerned, you are still at index 0.

This may not be the exact problem that others are having, but it is something to consider when using start.

**Comment by tangbc** [comment]
@aldenozburn yes, what component can do update scroll offset is base on Vue's `data reactive`.

**Comment by MLYC** [comment]
当virtual-list的子元素为组件时不能滑动，但当子元素为普通html元素（例如div）时可以正常滑动到指定位置，应该是当 virtual-list的子元素为组件时，virtual-list初始化时子组件未渲染完成，导致即使设置滑动但virtual-list的高度为0。从而start、offset失效，这个能解决吗？谢谢。

**Comment by tangbc** [comment]
@MLYC 试试确保视图渲染完再设置 `Vue.nextTick(() => { // 设置 start, offset })`
