### ISSUE TITLE
when list is embedded in a tab, it sometimes crashes

### ISSUE THREAD

**Issue by sigalalg1** [tangbc/vue-virtual-scroll-list#57]
Thanks for the list code, it's very helpful!

I had a problem while using the list in a tab view. When I tried to move from another tab to this one, sometimes the list crashed in setScrollTop (something like: can't set attribute 'scrollTop' to an undefined object)
Can you add something like:

// set manual scroll top.
            setScrollTop: function (scrollTop) {
                if (!this.$refs || !this.$refs.vsl)
                    return;

                this.$refs.vsl.scrollTop = scrollTop
            },

I think that this is also necessary in onScroll

Thanks!

**Comment by sigalalg1** [comment]
Thanks for the quick response.

We use vue 2.3.3
and vue-electron 1.0.6

The structure which implements the tab view looks like  that is skeleton:

<nav>
      <ul>
        <li @mouseup="selectTab('tab1');">
          <span>tab1</span>
        </li>
        <li @mousedown="showProgressIcon()" @mouseup="selectTab('terminal')" :class="{'selected': !isDetailsSelected}">
          <span>tab2</span>
          </li>
      </ul>
</nav>

<div>
    <comp1></comp1>
</div>

the comp1 code:

<div>
    <div v-if="(tab1Selected)">
    
    </div>
    </div>
    <div v-if="(!tab1Selected)">
      <comp2>
      this component contain the virtual list
      </comp2>
    </div>
  </div>

Does it help or you need more information?

**Comment by tangbc** [comment]
@sigalalg1 
I can't reproduce this problem, can you give a example demo link with https://jsfiddle.net ?

**Comment by sigalalg1** [comment]
We have a complicated page, I am not sure that the problem will be reproduced easily. 
On our systems it is reproduced rarely. But when it is, the app is crashing.
I  guess that's its a matter of initialization order. refs.vsl is not initialized, and setScrollTop is called.
Isn't it better to add this condition for safety anyway?

**Comment by sigalalg1** [comment]
Thank you!

**Comment by sigalalg1** [comment]
Hi,
The same problem reproduced in the function onScroll. Is it possible to apply the same fix for this function also?

Thanks

**Comment by tangbc** [comment]
What's the error info ?

**Comment by sigalalg1** [comment]
the function onScroll crashed in this line:
var offset = this.$refs.vsl.scrollTop
message from our log:

'TypeError: Cannot read property \'scrollTop\' of undefined',
     '    at i.onScroll

**Comment by tangbc** [comment]
The best is that you can provide an demo of a stable reproduce, otherwise it's hard to deal with it completely, maybe finish one then case another.

**Comment by sigalalg1** [comment]
Can't you add a condition before accessing scrollTop? It's safer anyway to check a variable before accessing. A demo is very difficult, since we have a complicated VUE template. I am not sure that after removing our logic the bug will be reproducible.
But a code with safety is better regardless of our problem

**Comment by sigalalg1** [comment]
We are using electron, with nodejs, so reproducing the issue on a new small environment is problematic

**Comment by tangbc** [comment]
What about you debug and change this component source code in you local env ?
After you fixed, you can list changes at this issue or make a pr, is that ok ?

**Comment by tangbc** [comment]
@sigalalg1 Published new version v1.2.7.

**Comment by sigalalg1** [comment]
Thank you!

**Comment by 8BitJonny** [comment]
The Bug is back.
I'm sadly not yet able to reproduce the bug within a jsfiddle but when we just imagine that `this.$refs.vsl` can  be undefined then we notice that the current condition in line 271
https://github.com/tangbc/vue-virtual-scroll-list/blob/fe5226dc4960b1d6b100fa56938627f2b8941f85/dist/index.js#L269-L272
in `onScroll` will fail with the error `Cannot read $el of undefined`.

When we change the condition to be `vsl ? (vsl.$el || vsl).scrollTop : 0;` instead that it will successfully scroll back to the top even with no wrapper defined.

## A bit more about my setup and more information about the cause
I basically have this setup in nuxt where I have a dynamic url which defines which filter on the list is applied: `/inbox` as url will show you all inbox items `/all` will show you all the items and so on.
Now I have a sidebar which lets me navigate between the views/urls via nuxt/vue router `this.$router.push({ path: '/all' })`. Now while switching back and forth I sometimes get this stacktrace https://imgur.com/a/jocKH2x with my parent component emitting `beforeDestroy` in between while this plugin is in his `mounted` function with a set `offset` but no `vsl` which leads to this error

I hope I could provide enough detail and maybe I try again to create this jsfiddle for you
