### ISSUE TITLE
在较新版本的 Vue 下使用，拖动滚动条会出现闪动

### ISSUE THREAD

**Issue by aisin** [tangbc/vue-virtual-scroll-list#72]
当组件在 Vue 高于 v2.5.0 (含 v2.5.0) 版本使用时，拖动滚动条时内容会出现闪动，拖动稍快时甚至会出现白屏，但使用 v2.4.4 及以下版本则无此问题。

可以参见 DEMO：https://jsfiddle.net/aisin/h6u2km1a/34/

**Comment by lkho** [comment]
It's due to the change of nextTick implementation in Vue 2.5

https://jsfiddle.net/llkho/j21tmq85/6/

The newer version is using `MessageChannel` while old one is using `Promise.then`.
Maybe the nextTick makes some difference in screen painting. I think there's not much to 'enhance' at the plugin's side.

**Comment by tangbc** [comment]
It's fixed in version `1.2.9`
